[[Pango]]
arch = "aarch64"
git-tree-sha1 = "4d728023f70018a14c4839644dbda6e36d50eead"
os = "macos"

    [[Pango.download]]
    sha256 = "43c987cd8bd0eaf9fcc6ff57b5b6d394c50fc42c6b05e853184b70779667b8c1"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.aarch64-apple-darwin.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "97999c3fcac83a789cac8b867c03ce0c95df286b"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "925c849bf6f1d196e5903c60e6d74597eab72b78ce18a2ebda6eeb9840e9f2e9"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "0c84a158ffec47963729f5dc54c3b2dfe151ebd2"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "2f5de14e80503aa32ff47b27722770055450df06eb3cdbe6e62b98c6943a168a"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f9481dd1677514f47be081e227e0e48a1fdba2a6"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "5d7c8753b477b9103d0e8f15d721a2ca5c9845c397117c8a011525ab97a4d514"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.armv6l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fdb0daa2795292a6514cfa3d763d7aa1cdb3fa8e"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "8ffb4084ab6f207b02751c837ea73f565ddbba8c9cc1605303c1be7bb32d8614"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.armv6l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "304edb0b2ce7f91eff59b6a52218876ffb6788a8"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "01dbbbec0dc5e60f532cddf890845d25d5bc9366db717bc2ac108b4c297f826c"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.armv7l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8563e8b9bdc462381d1a9527659c01a36d2b9b9f"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "8e10912ae4513077b231fd87103d053184e6764c63d6aec94c70a26137d058d7"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.armv7l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "2928c66545cbf98933d3604dff5b73b76bc114a2"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "656b7575e5b9dc449726ab09354f5f601bcc30462a189547ffebdb2f1d0e581e"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "a55375abcc7a5789d795c1dc6e9b35d41b421cc0"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "5ca94adf82d6bf669ae018c062a421fe7c71bd823a593bf66dca85635857ab09"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.i686-linux-musl.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "828f8ad4efb7ff426ab1de6f77b6fb485f73d725"
os = "windows"

    [[Pango.download]]
    sha256 = "4c4e5c3e0bfbffb64ea817f74aaa56f0bb251d705ca356bdec74ffc402f463e5"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.i686-w64-mingw32.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "a77264176f37db1e19d5123a03355c73b1bf6d24"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "427c1e5bcda83f6ed7fc8c70ecd7a24785e95ba73b404c91613a195551f0e324"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "eae648a5af4808092f7df013774d731d6bfa1dc9"
os = "macos"

    [[Pango.download]]
    sha256 = "4b10d301d6c88833c7c256f17dacdb4746acbff420055925a661bf15426bd8c8"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.x86_64-apple-darwin.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "e738a1c8ef86ea56fd7a2fb63a7bfede4556384a"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "3e5ca2a5d8ce98062587f5275d4303c15d4a340f534a520a0560f571d0060847"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "c8f5715211af21364861f04337fbe41d426abb01"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "aeca46fcb5f4879c47f38e9f457096e082abf11dc878e857e29a0be4ea6931aa"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "a4b468b8ea5c8db203538e6fc14205e09047c2ec"
os = "freebsd"

    [[Pango.download]]
    sha256 = "8af609828e57c7ee7be2134677779528c0e3dd057117ada718d9ac750d94711b"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.x86_64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "a55c96814be629f53619d5013c770c8d59353ebd"
os = "windows"

    [[Pango.download]]
    sha256 = "25f77cc27261fb64b2220bb9c3de6756935ae643e08b4b7375e3b29c097aebf5"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.2+0/Pango.v1.52.2.x86_64-w64-mingw32.tar.gz"
