[[Pango]]
arch = "aarch64"
git-tree-sha1 = "80313ddf67e8279ac953ee2b6b337798f6ccf782"
os = "macos"

    [[Pango.download]]
    sha256 = "180e14906a429c8b476b165f7dddd249c68d84d1d1dd2b33f244707e05cb9a4c"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.aarch64-apple-darwin.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "43629173677d5d334547f4173467e73f913de9d0"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "7a009f12f9640847678b06f76eea43470bd7b920edb3083e688ac2acce723af5"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "cb2f906f273f2f799c8bbf5e54b1fe017ad15da9"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "ccb133ebcc3a10babb1e65328011e352dba1890a52b4e21ac246049ce2aea1e4"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "0da7685514684fcd0512685d1684e6d8b0d5ef86"
os = "freebsd"

    [[Pango.download]]
    sha256 = "2d335a73f27b164dcf8f1af3b638cac515c63393ca96a288369e55504471ca83"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.aarch64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e29a0c995db2d00aa425cca14a16d3578a086e2d"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "cd2689e2d8d0859e88c79093e25c57eb265272f5b3d44ea49dad42697e0dd91b"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.armv6l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7cb95f7fe4281c3a772d5371ac2d59733d38c0a4"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "3c05de42505fd527954f5ce66f0d1e18d5e394933d1340014b95722d239b6fb7"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.armv6l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "113c2fad424b56a0d0e444eaf7f3d1c02ec79ba9"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "2a15a1ced575cd8657e0ea0f45723e733db4570318f0290299e8575738921178"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.armv7l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "597fefae5815e62567c505f1eff0f18c47270510"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "d0deda6f023821f94930e87929da0f9d42c646c826270fa840bc751101fb9c18"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.armv7l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "d37cc448d67ba50f6766a5e1dd5634fedab76b01"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "6443f549e9082c3d1889683aaf6c6ea9e71a35b0a6b2b0dde8aa61779af4817b"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "7262da007edcb0452b51c11f7de5df5d7551bfd0"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "f48f784505a82c994abcfd7c82ff68c25a935762232e9fe07e98b9edf31da8c9"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.i686-linux-musl.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "4ca9d05720cac0b97421575efa842bbd53fca533"
os = "windows"

    [[Pango.download]]
    sha256 = "e766db254137b82282bcf7e23082b01dbb1b70d3cce01744f915278bcd11e011"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.i686-w64-mingw32.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "d6b42c1f0967b204931ec2c992be957c81dfb2d7"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "00c5697f8b18cf44d9915bb3a4caa5d6911c43a29f7c650f687c7e8e510ffb8c"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "riscv64"
git-tree-sha1 = "191ccae5b1d9e6b6a01b495f641f307b6fa83ac5"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "18df8731b89adf23d3b49244143407d4b506b01f85e5863ed83efac5f544ad90"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.riscv64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "b0b028a30a8e160b6b128d768321ccf2a7693544"
os = "macos"

    [[Pango.download]]
    sha256 = "3bbe901243148eff606c878d7b5c9c7af33ebbc456f30abbd476a2bd8ac63f7f"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.x86_64-apple-darwin.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "5b34e010ca7a3d88eeebecbc7a5b39ad72e33323"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "f1363adf339478a51572bd68b3b93061446e4f8f1d69316a339de4480e5e214e"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "c274c41492be12bcdd209191f7ccb7e0b93bd207"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "8afb02b088d5a00928c7b7b575e714b9f8b2e7959a245f051091f0f939c9e943"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "5f0f914e48bdfbc88d3ae24170754733c518d8d3"
os = "freebsd"

    [[Pango.download]]
    sha256 = "e3774081477fdc1d7265f9347e60495cb1383ae6f5e7791f90c88e2a7f1b3bd0"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.x86_64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "346de546666a50f63974855fda2fb069eb5ec462"
os = "windows"

    [[Pango.download]]
    sha256 = "64b88d8c7666f0c7316d301114d6571ccf8b0524abf0ac0db7f85fa64af63247"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.3+0/Pango.v1.56.3.x86_64-w64-mingw32.tar.gz"
