[[Pango]]
arch = "aarch64"
git-tree-sha1 = "188a9d9a2b9538a19c73ff7730df9162e9d509c1"
os = "macos"

    [[Pango.download]]
    sha256 = "483c46c9aeb6c936b842b1d1f5604631ef82f9ba33dd61b4a1d3e75678cf3e62"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.aarch64-apple-darwin.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "8cda8b2f6a83d5d83dd7f4f4e3b789ed735f2535"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "b2915c728b6670947dfe23b481212c29af2fbbd3e8e985ee8da29753770c8c0a"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "4623d5923a1de84fb94eb49cb6c4edfabad8f356"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "7bc731067a3374b33b6d7e9a42f1a74289992000c325c66a3c6b3b158c608ebd"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "f5d3829efb126523b28b876cd100639aa0164e97"
os = "freebsd"

    [[Pango.download]]
    sha256 = "a1afa71537bfead705395756201216fd6c2fd0e396aaa44391a192d7e1c99f46"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.aarch64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "867e0c689fb22daad0c63d0ee8a25042f2f2c0ff"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "4fb499f9c8a20f161e69ec8998d688f14174e196e735455ea0906d87a7456df0"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.armv6l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a21d8f6d8880045de6022ad2266d6d1fe04ec856"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "615deb9ea5d64f9fab031bc866a6df661b8a59511e5d4a0e769b1f1e2833a6e8"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.armv6l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "383b5e1d53189831fc00d27171c95f702ce57c92"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "239d96fa0e88b98eb557ac0754013248d2870d3c6d1a01698a69fcd415cab2ae"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.armv7l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "60e0ad02f2d6d371b59c6ec33829a87625b2695c"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "c48aa4e68f4eb76e757d4f37e1e29838716fbf0b61c5c35f856a70198a91579a"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.armv7l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "ee80f42f13380ed2a84079e8251b760c6cf750c6"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "cd729325e9b0f15374c02ad01fa5840ad7e17eb7b1d07589d34fdad9acf7f3f6"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "690063f2a0f1e282a4382f10e652acbaa0de9ccc"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "3c0e60efdafcaf78a10aafca1acaa45c0b938ac19403c9156fb6dda29efb568b"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.i686-linux-musl.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "c3d7d22c6fd5efa5d3dd6d8626a6d266d2d09d78"
os = "windows"

    [[Pango.download]]
    sha256 = "c58c6e9e2e9e41523f9bf94f999f28f668253effb21122b5092d91f303975d13"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.i686-w64-mingw32.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "f7fa8d8fb3cd2d4e05c7a7181aac7c75ae38c254"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "29a184b7e833fb8d85352c4a979c8e124dce410b634918ef987c4904f26ca936"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "riscv64"
git-tree-sha1 = "06e61f95147cfb387006bd4a15d22e8a08074917"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "8debf21c1149f496ed36640b31d1d81fa566422d157dcf9f529e50578dccc1fe"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.riscv64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "c6cccabed46f4b882eb49af3d1060b9637f85af0"
os = "macos"

    [[Pango.download]]
    sha256 = "b4d92279b3d94483a1c336f4849982fac08cb8ebef9eb9e15619a3f6c4721f6a"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.x86_64-apple-darwin.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "08db884c568df7d8a82ec8d230568af2aa414513"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "141e72cae7d4c6b8a431305d07c96d3e25e53bf925799cf9117406a7d0671960"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "c2fc3ea58585d21762c456717333590838a90a1c"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "d70e4012787dab48eebe4420f0644d131e099df4c3b116a52ca6ec80df44c4e1"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "7043821f76b16980193250ea9587c9778fd7e143"
os = "freebsd"

    [[Pango.download]]
    sha256 = "50ad5ee0d98b407943c38c498f1755468417daab061ddc89ab969d69d7c0b28e"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.x86_64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "0c7cf80c7a6bf02f80903a86a4b4c2e48471d186"
os = "windows"

    [[Pango.download]]
    sha256 = "f84cd773725b174ca0ebe10bb90c3da0032f6b6ecd2f66447f824bf48cec6da0"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.0+0/Pango.v1.58.0.x86_64-w64-mingw32.tar.gz"
