[[Pango]]
arch = "aarch64"
git-tree-sha1 = "5fe999ebfbef574fd16d6cd5a1a9740ca64bf7f9"
os = "macos"

    [[Pango.download]]
    sha256 = "d56a72e15e4bf7227d39638f31a24d8929134e7bf29a4e640c16142777006732"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.47.0+0/Pango.v1.47.0.aarch64-apple-darwin.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "29ecdfcd95dd88bdb0322c0f9abdebe9dd4fd655"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "865201e0a339a69b51bd4282550464dc91f6059c191cc1c3d7171824099238d7"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.47.0+0/Pango.v1.47.0.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "f56f13f4263f5a9379507424c062de5716d2a6a4"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "5edff54a6eb24a8c744037b9f0e119adcabcc18436aa8a89681035b8f1d49e61"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.47.0+0/Pango.v1.47.0.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5a22aa29c87a05fd32f9b9b49c95e01601712407"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "e49ced523c9f838b8164b3a855cc5f018ad353eab23abd6b7bd4e1e8cd91b41e"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.47.0+0/Pango.v1.47.0.armv7l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "43aa1afdb9931b0b29ae42f6f063c9caf88d3241"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "5c2f52e3a36f44b95555fe66386d1b203c77cfa65625f0bafb9bbee310acec23"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.47.0+0/Pango.v1.47.0.armv7l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "087c52c76b364238c926120efc7182b2672d3dbc"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "b96acec058ed06238d649b0f1b7d4f52fbb1b947ebbc27fdb247e939b84d1c48"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.47.0+0/Pango.v1.47.0.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "093e4695d750ee6be79445855bf219fc69452692"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "e4d3a9941edd9e35b55aafcf897f16f1e07500a1243dd7ed1daa23fc32e17168"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.47.0+0/Pango.v1.47.0.i686-linux-musl.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "62f1fa7c04bab49bf6f1108a231a752d01e2bc8f"
os = "windows"

    [[Pango.download]]
    sha256 = "0310ead8b21c67a71dd810294b9b0a273e485c9a8a5ff9713237c6fe02ef39a0"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.47.0+0/Pango.v1.47.0.i686-w64-mingw32.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "50d9f5a56904cc418cdc1cd57fb2c402c09acff8"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "997b905f03c9d064fedfb1581bcc568fcdf3a3bb30267f2e262be9dddc9af1ff"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.47.0+0/Pango.v1.47.0.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "0d3914a2e909cd9c7e29e2e254e8d1886ad3bff7"
os = "macos"

    [[Pango.download]]
    sha256 = "df73c7c7fecb0d892ee0847438541ec12a0db874113ddc9dc1c7bd8c49efbc3f"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.47.0+0/Pango.v1.47.0.x86_64-apple-darwin.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "783bdcb1f64473a5b79a2bca8920a3a271c4d81a"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "37cee9801aff73f50520da5096768ac06bab1d1f7982a8727113fc17554f7210"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.47.0+0/Pango.v1.47.0.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "e714b4dd1e0f5c90fb23d79af4ab63b277657b1f"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "10f5cd3f1109d461ccb47340d6ed4889c6ba1fe8de7a655ff2c3f8678898ee08"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.47.0+0/Pango.v1.47.0.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "635c4659b7a57dc58d1118b91e70ef15ca83021f"
os = "freebsd"

    [[Pango.download]]
    sha256 = "e3e0db9799a891ee07e59e7fc6290efa655ba1a91ddbff82b4e4641de83b689b"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.47.0+0/Pango.v1.47.0.x86_64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "30ca91ef7a1e9709baeaeb513cd7568b87374f9c"
os = "windows"

    [[Pango.download]]
    sha256 = "5a3dc2e609aaed2bbaffa773fd4b945f174f933707232e894988a3af02b49d33"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.47.0+0/Pango.v1.47.0.x86_64-w64-mingw32.tar.gz"
