[[Pango]]
arch = "aarch64"
git-tree-sha1 = "affc36733a0272c4d38b726478f4b42679f65b08"
os = "macos"

    [[Pango.download]]
    sha256 = "78bafc118f03801cab74e6c271fc86c26d7ff9f999bf0b05292fc5f13a970559"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.aarch64-apple-darwin.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "89f14c19c28801c2d0f377882fb507135fb62cc2"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "66744fe5b519af7ff3723fa27bb09a83d4563f046ed47659e4f5677f6749dece"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "113e92e670f59389052f1143e639b56382e74af6"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "4c3fd30fa5c1d7f9a859d39b1e01ec34d7ecfee115a112fbf9db0fd4bdba70aa"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "b24dc6e11a238d194f7c79454aa110bd23a083cc"
os = "freebsd"

    [[Pango.download]]
    sha256 = "d8382966ac29828853a3ac290ca5cec89b905367c2e81ce18b3bff1ef3625e51"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.aarch64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "87df4cc5320854fe401d64fe28e704374a6d2e0e"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "5226925230c138f09389f417b6bd348651aaa397aba7ea7d4ca8891870c02d7c"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.armv6l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3ada1fed87b9ce0b23e25da96661cce1947b70a8"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "973401f81c4c9a2a3c40d4e45f0b3d6449b92ff6ac91fb37e6ce1c0df758844a"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.armv6l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4b8e0fb72e50bf8745ae6a41c38ec539d4f7e735"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "bdd2124c064a7bfd07d761b8b43a2079630ef9e9f27c6a4d47dd70c0ddcc234d"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.armv7l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1e1ae5e44bbbf652f51d0a035b74bfc4db488dcf"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "db95f5247bc16916678d8d29c94554b90d04f51f3d29f5ded803fa627552f4a3"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.armv7l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "31a6685f4320823f4a7197cdb652bd51d0b4dfb3"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "f4faaec6978b8a318fa280de1b3d4875dad72e82a0d2cb47a4dab5a7795af056"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "73a4b09f85cd825fe13a8c56627f62ac8a1bdd17"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "045399b9fa838a308f4e112dfcc89651e22c8ce5abdc406d0a0c3cc9b0e316a6"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.i686-linux-musl.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "56519a5bb3a593dc98657b8b3b433c9451248299"
os = "windows"

    [[Pango.download]]
    sha256 = "432277aedc17d5cc45125cf59b22319728c11fa829aa89fa43d82cf0aa291a7e"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.i686-w64-mingw32.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "039f62da1eb29232917a9e74e898b61665c833b8"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "55e1666dc1d08915d8ec50c94d30db9c528fda1a58358391876ace1e50343777"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "riscv64"
git-tree-sha1 = "73c2a9511cac6fa041ff326e159711aa4cfc7ba9"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "13a555b70da7880f0f85f1700531ac8561fb9aeb2d0cedf58917e3a64cb4a9e2"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.riscv64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "11a4c39a1b0a340a77b6326a46c6f7aef15b2c81"
os = "macos"

    [[Pango.download]]
    sha256 = "cfa77fb7d301e6e6db517e21bf8b4fad04f354e0e0595e551a5ccaaece30bd5e"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.x86_64-apple-darwin.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "2ddd5ffa5c5c915c7380ddc1e702176ac88c4d30"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "3845718c81fa60aea484450014521ce5e3a0b77995ecf6e3e117a96e54c66164"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "57de52d0f626d0fb6ba8580e1b5ed508f4a3a55f"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "997f54de13ca5cd02b2649e45a5bb6e6e5d3203ffc744d4e5e555be948fb16a1"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "18394fd4acd73e695b91a92b6fdf91c584a77190"
os = "freebsd"

    [[Pango.download]]
    sha256 = "4556461f3ceceb68cdc32a51c9aeea9042e982df8e9f7557af10d56738fc151d"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.x86_64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "0732b814a8e21b177b57c3094944533bfd566cdf"
os = "windows"

    [[Pango.download]]
    sha256 = "0dafb2658245c1b12b3f75e474c93280a888bedc767a794311d5449255274272"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.56.1+0/Pango.v1.56.1.x86_64-w64-mingw32.tar.gz"
