[[Pango]]
arch = "x86_64"
git-tree-sha1 = "ea8007083e90dccda7ffccc3c372f9ab838d89d7"
os = "macos"

    [[Pango.download]]
    sha256 = "4558ba65673be5752aee9cf3c509c56ab61b2a5521f285e857fa82063e424760"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+4/Pango.v1.42.4.x86_64-apple-darwin14.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "5e27bf5b2846261be45f09afcc1ac51b38516e30"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "fd851fe037a847d85ab9699b538e63d7efd3f038bc6c270e945aed39c230625c"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+4/Pango.v1.42.4.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "3312b010273d11b7d2d1bbd9945bba16444891f8"
os = "freebsd"

    [[Pango.download]]
    sha256 = "71e8a8593d99037b5d5bf3b569a877ddd853b303150b38a28faa5202a3959854"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+4/Pango.v1.42.4.x86_64-unknown-freebsd11.1.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "6b6bb1082866aeb68200cd230daa0594da2bc142"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "e501591b4fef489a8a426708e656851c5eece7be8a157e8e92c9d2997f872586"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+4/Pango.v1.42.4.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "accfb15e23395e9c202c549a5a24755389aa32ab"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "c77c2ece7577f94530bccef78c523effc59335afb583d7f659003bc592e821a5"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+4/Pango.v1.42.4.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "6ecbb83fe4846f81ce3e164d64ca4bcdb1055a5f"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "f078bdcdb6a84ab4fee1ffcfbb9057a52beff0e6b071c7196f2c50d1f0139984"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+4/Pango.v1.42.4.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "640d71653ad18a43b4cd2a3e75df270c371a1d35"
os = "windows"

    [[Pango.download]]
    sha256 = "4a6981635329982c16d6854614e9d4bd298cce8a66cdfd102b64490711b41b67"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+4/Pango.v1.42.4.x86_64-w64-mingw32.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "07e67dbec41f4da4342cf3b4d4f267069c79b0ca"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "0586189200b8f80e100da68ceb9239870a8c02e1b5aa0abeed80e6d5c36c7a50"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+4/Pango.v1.42.4.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "armv7l"
git-tree-sha1 = "0786b71b40afa591985e381b7a701648abdd809d"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "c50fa5e7fa2d4bd6cf33176f1c48107c6284fc08a9d498ea9d87809bf75838c4"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+4/Pango.v1.42.4.arm-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "dd12eb8c95d1c2d07cb0f2315eb7fdae1a972041"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "2b4242b38035786a362f406d79a0a3c5da090aab16a99697183bb76531ecaa04"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+4/Pango.v1.42.4.i686-linux-musl.tar.gz"
[[Pango]]
arch = "armv7l"
git-tree-sha1 = "b6587932e853fc22079967867a5ea6c3ddf86ea0"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "aeb8a28acb445fcf09e9cdacb39ff703b31c4cfb94feb08a68a6b01441233b9b"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+4/Pango.v1.42.4.arm-linux-musleabihf.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "768d41af818562454c7d01c323ba1398af009b70"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "ed90aa7689080ff203dd32fa19cb091f5d512a8c8ca47e5d96aa5436430bd171"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+4/Pango.v1.42.4.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "d21daa872d48adfa144cf114399cd3b731de724a"
os = "windows"

    [[Pango.download]]
    sha256 = "4350462e09741fe7de98cab3eb63b701ec36477680ad9e1e19aa26908c0b094f"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+4/Pango.v1.42.4.i686-w64-mingw32.tar.gz"
