[[Pango]]
arch = "x86_64"
git-tree-sha1 = "03fe8e12ed268cf9772a88d40c843848bb79b325"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "93bd903ed84f8c36ff18d2d662ce0b9cbe99e34380dea504f7d8b9233b9fa18d"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+1/Pango.v1.42.4.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "bdf7d7c69417158f5ce8879f3e55094fef48554f"
os = "macos"

    [[Pango.download]]
    sha256 = "c970983fe8fa7adc8c996c42b8ddb627e50c563b3b2822e8b21fb920c39bf3b2"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+1/Pango.v1.42.4.x86_64-apple-darwin14.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "580eef30ff56b04e48b8b2bae56c5ce270fe151b"
os = "windows"

    [[Pango.download]]
    sha256 = "807e11b6a67fbb00980d3bfaafb1e74e8d626ceecb9bcc87e91256f95bca9c9e"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+1/Pango.v1.42.4.i686-w64-mingw32.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "91239c13f0ca86741e256c331072aff3764cc75c"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "ba1603f4675ec9475a242c4e85aff108889173a72bc421c643c502bea895ecbe"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+1/Pango.v1.42.4.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "8617ab443d06654518c32675026cf025f51c15da"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "ca8858b1aaac13538a496f2e63b5e9d1a27b704c67c3d7ac5d6a223632af8baa"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+1/Pango.v1.42.4.i686-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "7b9aa0cff531a52f5b1e5a209070ed5483b1ab4f"
os = "windows"

    [[Pango.download]]
    sha256 = "52016155e62335ae3c814fd9da7ca13cbe9df4d9a05be72942fafc59e8bcc823"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+1/Pango.v1.42.4.x86_64-w64-mingw32.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "406ad3421e7d006e364e35e3ae491f1ec12522d6"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "4852575d17dbe272ddd8bf4adf210ad0b58b533a595907d95376ce858d372787"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+1/Pango.v1.42.4.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "41a34ca038214f05e1e953cfa34f1cd09bd3b125"
os = "freebsd"

    [[Pango.download]]
    sha256 = "3ce85286829ac903202fa01b1f55b2d5fa23d5e8651f55f2a17da909f403c982"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+1/Pango.v1.42.4.x86_64-unknown-freebsd11.1.tar.gz"
[[Pango]]
arch = "armv7l"
git-tree-sha1 = "94bfc2dbeb2964bb8e5fa80ad775d8d5a8109b95"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "de289e0972db1c8d098b4a4b159b38e04f9ab51035143b537152e428afc418db"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+1/Pango.v1.42.4.arm-linux-musleabihf.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "65b2379016a147f6e8858ea55ee63fe1ebcfea1a"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "6f14458ed2e02bd3c357a2653372c270baf56eb32b5d740c2b075289251d7fa6"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+1/Pango.v1.42.4.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "d94d099a00d415e33b4c1ed5145ed7a8f2123a75"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "523612627836c1e5ae529259d73667f623400d57e582f8f26fb91765dd892262"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+1/Pango.v1.42.4.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "76e729c58f86985d34e5b235e86af8dcb6a6d7ff"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "8d01ad34b8804de72b4d00bc5dc81c072bde087d18ecb67fee9cde9fa574e276"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+1/Pango.v1.42.4.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "armv7l"
git-tree-sha1 = "9d179c182534b0296a27ce072663b80f3e6f559e"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "0bf5b57a169904138b663375f13956d3945506a5c69991d1807db946b32956fb"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+1/Pango.v1.42.4.arm-linux-gnueabihf.tar.gz"
