[[Pango]]
arch = "aarch64"
git-tree-sha1 = "61b91ec9750b43c368cc644c01ef29f3d400d98b"
os = "macos"

    [[Pango.download]]
    sha256 = "719a29468711d3c238536a1bf7ba520ce2bbfaa8839b3462e72f96d6956945e6"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.aarch64-apple-darwin.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "44139343c63bcfa99f44c8b2af7f8ba0166bed52"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "6b9004f619ada7557ce7f48d63b1dd6c81853698cfef0497c4e0f877d65669cd"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "47247809441e1cb0c3d0848b6e0d35f5b545fb0b"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "1d964f7e73ab57b8d8a0aedcea5912a3c197dc5e11fcbd5be3aaad2873107780"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "87d42476bdcb946441bc5c4a01ca8fd3d4bddfe0"
os = "freebsd"

    [[Pango.download]]
    sha256 = "d58262d163559a6740fdf5447fd95bbbd8602f130be5d788bdc5f0e3089d17be"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.aarch64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "409ca7f9ca5382ebfd5482cde3d6c8e68cbc68ce"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "0677cc1f46771b07fbed87215fa7c61951e3d9325fbfc1b26286d32391950d80"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.armv6l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "43aa47ab1a50c0a7c5fedd657b6d60c6e27314c5"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "6f3fa456e21084450979aaa5b00acb986684aad2a26ec580110b19ac83c91770"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.armv6l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8d4bb9ff46469f9e390ee93c9649e59bc6d9520b"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "d44dfca5fbf2509579e2de4a4258cd8475790814b7fd8e8c96ccbe9dd3232ad8"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.armv7l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a4799b9b8662285583851267cac2a83a6d94faeb"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "e08d4f26bf00cb698350eeb45ce875976af1945acb8044565e5964cac9c530b0"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.armv7l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "bdcda5087988b6b3eaadd58e4b9c15d7a9ea19a6"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "6fafb4f6aa1f051926e46ddb9fc3945e382b21943027b28cc137bdbcbcc4bc3f"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "eb177c96dbf5d8dd91d8b2bd56d55682b683f88d"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "7100f044cd84bd940d197a136832e803bf66e9e1f5d4a0ee7100376a7e5bd0f2"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.i686-linux-musl.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "73587d0cc94dbee40abcb1b074357d260915db2e"
os = "windows"

    [[Pango.download]]
    sha256 = "1d8b525f10c202a5f4d312f125cf2c26cc98013074a9dc1fb8ff232106be5a7e"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.i686-w64-mingw32.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "da9adca26371656098f6a76375d040aba9701235"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "d4d77dc97a13f557526aa966b2cc3e3813b5b0f7cc61aed5ed5032e78e0bedc3"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "riscv64"
git-tree-sha1 = "e9fcfc7a999de68d1706021a05a4acfd430449ef"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "a97e2b036b9f1bb3a754e2bbd7ddb9a5aa19b655e658d17afa52507e11209ee1"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.riscv64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "b42b8061cbefe4395c120920f73673e3b17cb0cb"
os = "macos"

    [[Pango.download]]
    sha256 = "b88f0367d3970f59abf03adf617e31068c36d9025dbff9e8ab51956ecd3d37b3"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.x86_64-apple-darwin.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "99d60057d12d06a133c92bdc6e07757e710cd5c6"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "96a43249ba9cf5c4c7bb4c80181da54a7a0a276f2f7385ddd902c2b78578b659"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "8595675c3beca03f890caab84e7d5e4acbde90c9"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "a913b057b340ed67849aa785d05bc7ae75c621a4817661aa18df0252be6a4334"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "4a369463959f78edc335929847d8afa446c9fff9"
os = "freebsd"

    [[Pango.download]]
    sha256 = "3f9d468c35168d1dad8ce84763e5c643624902c30780803669e18e98c8181cfd"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.x86_64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "5b81c38058bd15c772646e71dfcc2eff79ad3428"
os = "windows"

    [[Pango.download]]
    sha256 = "5372ac697bc814f1e192b632fa05dd0fb0e4b28fd0325d4a7f350510a7d547b7"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.58.2+0/Pango.v1.58.2.x86_64-w64-mingw32.tar.gz"
