[[Pango]]
arch = "x86_64"
git-tree-sha1 = "8309a1990828686e29861622541858fc6edf3a75"
os = "macos"

    [[Pango.download]]
    sha256 = "58aa2be032a5fa0c55dccf11187a822f27c0272219cf32b5a73bcc2f8dbe1839"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+6/Pango.v1.42.4.x86_64-apple-darwin14.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "81b70009a994579b79246d0a94f921d43c88071d"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "037d70d9fb51a025bd2bd19e2b013b1a59e11a7165ecbd77bc11a34cdc539daf"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+6/Pango.v1.42.4.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "d920c775090b967c5ac6b50d7dd16f338790bd14"
os = "freebsd"

    [[Pango.download]]
    sha256 = "6f816b40d12117f02af9a24114a85754c31eb9ed8170ea453e6d2ac550045dd8"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+6/Pango.v1.42.4.x86_64-unknown-freebsd11.1.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "984108cbf30f9c7f32892f47931643ade57193d2"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "14eb39da578ba8ef45cc5fa07bcc99c5ea792fa58be21d2196dffec999e073bd"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+6/Pango.v1.42.4.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "6dab95ad75c42b8575e4367e4c9604368a284745"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "5757188417145a183681e9699ab1be1cdec0e5916f927c2a1d954df271b114b1"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+6/Pango.v1.42.4.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "56a96cbeffe09e8c7d7f011edee0ed9eeabdba43"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "20fae3558fdaa9cd3e018e4b9af6c598a5a5883390682689246146176599f54f"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+6/Pango.v1.42.4.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "97e64bc5f10f2192e37f19dac829408e6a35d7aa"
os = "windows"

    [[Pango.download]]
    sha256 = "2efba6558bbd3c43abe2e5586d418165da5b9e425c1054d82256b867180ab8ba"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+6/Pango.v1.42.4.x86_64-w64-mingw32.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "fde5d3bd2ed4c878434daabe82cbfb066de67ce6"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "855308853ffbbbdeaa48490652f97726e5bdf90444b97ade3d7e1eb0278d6ac8"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+6/Pango.v1.42.4.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "armv7l"
git-tree-sha1 = "8ffcfa515f8801a163e1f753e4e17bb5c05c8cd2"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "dcb4f81d98b1e7abd95b10ba28772fe7273cc9271c4913b270aecc7953d02014"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+6/Pango.v1.42.4.arm-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "b8474be7cc359ebbca6e1e56ccd96d3ea8f28652"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "f687c20acf97ccba442484b8ecd65e4800082f2341d182d64aee27048dfc35ac"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+6/Pango.v1.42.4.i686-linux-musl.tar.gz"
[[Pango]]
arch = "armv7l"
git-tree-sha1 = "ab579d03af59f36dbb10fd26aa1bbd91dd1901e3"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "e6eaab40302c37bcdcffb9bf6fc966761d38475f6aafff6748298c59a1b056ed"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+6/Pango.v1.42.4.arm-linux-musleabihf.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "5e4b780c38b888acb0dfeddaab71ebcddf7823a1"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "d32b0897c981948e05454c5b71b28fb8b5f61f519597a9f71a77d03b7122cb47"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+6/Pango.v1.42.4.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "a57fa4afe171c764c53d885ab4b0fb5a5779bb3f"
os = "windows"

    [[Pango.download]]
    sha256 = "3c15543e9c1bc48ba601ab52646c0275373e67c0742cc72aebfd617c7efe73b1"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+6/Pango.v1.42.4.i686-w64-mingw32.tar.gz"
