[[Pango]]
arch = "aarch64"
git-tree-sha1 = "b851ed4ee9a3305e991a1184b9b94ef0895abea2"
os = "macos"

    [[Pango.download]]
    sha256 = "407681e626f0f34e30b90b47a36d106e6117028a4788a7188660e9d3017c7e1e"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.1+0/Pango.v1.52.1.aarch64-apple-darwin.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "71f21870c699df8e53bf8b29308a77eccd40fc74"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "88fb1d48cd22876879e67b0ec25471f1c9771180291339959a68dba8ea64b655"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.1+0/Pango.v1.52.1.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "8516a57598c12dea6f4b8034593837e3034e17d7"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "d5d6c6f62eff703213f18595939b77698379809728dcd84f5be36a37de1d803a"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.1+0/Pango.v1.52.1.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3d8d580e75540c20af98fc9684d851339c423499"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "e1ec9a49950bfe4c6d03a04ef201f51920f55f36ee0d40405bd3b78649ab72a5"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.1+0/Pango.v1.52.1.armv7l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7a3d3f36426ed7d6bfd6bfa8c074dc7bc17bdd90"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "ba3066005f09ba3f4ea9707a755be816f2c2c4248928baceb033fafc71ebdc5d"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.1+0/Pango.v1.52.1.armv7l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "dd566ad683f71039aaa160e45d9e6cf64b8e70c1"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "75ae1114a6936b5e118977dda49150173467c8fc4ea171c14fd04ac54b54b705"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.1+0/Pango.v1.52.1.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "27197b63a6816657efa98a0b3b669b7ba8c7b571"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "2d27735e49d60da2842b4652413371b2b253d98a873b4e2d5dc5df1b99e86f47"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.1+0/Pango.v1.52.1.i686-linux-musl.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "bc293e4eb46b06aa5b5df58bbd48df6bf5e833d7"
os = "windows"

    [[Pango.download]]
    sha256 = "c56950fb27689c33d26569b4060cc5a5c3650b53d0c1be58c14a3be17f58d157"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.1+0/Pango.v1.52.1.i686-w64-mingw32.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "ecddbc71f0c5d1ffb03bf1276e898752ed192157"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "4ee045b4a210f92532d5b5f4c2222a3de9a3c2010d852ea99e60914d82fe89d8"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.1+0/Pango.v1.52.1.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "80b8948d1fa864a4974c0d4e71ddce9586311598"
os = "macos"

    [[Pango.download]]
    sha256 = "5850495374e66b5cdd3c775bbae4beef4456fd7b5d4b034f752de8b2661518b3"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.1+0/Pango.v1.52.1.x86_64-apple-darwin.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "f481e3d17005896699f4c17db2e446853ef7f00d"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "abd980b05d2de861c8e67712a1fa242dc707f68fff8039dc315a22a1ba0c501f"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.1+0/Pango.v1.52.1.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "944b54a981a6d89a02d1acd6cfec3b25d982bb68"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "f2a5e1e65f6bac44c1cfeedb6c33524ebff458523020a632ba6e1e0767a710f5"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.1+0/Pango.v1.52.1.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "8435c56c7e70a47b206356edb978b9da33ec2bb6"
os = "freebsd"

    [[Pango.download]]
    sha256 = "2a4f15c601520c449137698326e3d0d7cad922600f5799668d5770768675e9c3"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.1+0/Pango.v1.52.1.x86_64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "d63b72d439743512ce9171f374a24db8b7d2d53e"
os = "windows"

    [[Pango.download]]
    sha256 = "28ecede63b469255dd3d6262c50dd38d57d3707a5d4806f0a067804233845cc4"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.52.1+0/Pango.v1.52.1.x86_64-w64-mingw32.tar.gz"
