[[Pango]]
arch = "aarch64"
git-tree-sha1 = "5468acf0ab7d63c9fd87622c5355256ab61f082b"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "bf6e1afb9568cd1afb0b4b156f5f4fb62492d93a2a4438675fde32e46f844916"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+9/Pango.v1.42.4.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "baa963489807c72dd46f267526b905f34e6f992c"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "95fd5a781eb33535d944f124cff8b19d792ad68af7232f7f004bf2f0dc460eed"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+9/Pango.v1.42.4.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "armv7l"
git-tree-sha1 = "818ee66963131aba057976194ae45e4efbf5ee48"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "3ae514d749d474ce6c874e270988532ee78e43d950b751accef91f703fea918c"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+9/Pango.v1.42.4.armv7l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv7l"
git-tree-sha1 = "076ce3550f06493696ecc49a8846046521bdff4b"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "8464878486827dafdb71e43f3d6fa1c5b1e3c7004f11e7425c7f0cd679dfc7eb"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+9/Pango.v1.42.4.armv7l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "4da495b3cc4c269688fc27404927ea65725349ed"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "3c451a87da5a930ea75b07d5c815c64d5b9528f523b4c37d4c61bc5b6bcd8318"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+9/Pango.v1.42.4.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "91d934368f70ba3827c0a390dd3d79729c292811"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "1d49146e4e918ffefae9798232b91e48c72479de89ab356d1b49da693e60caf6"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+9/Pango.v1.42.4.i686-linux-musl.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "275e1627617e02c1c7dc57d8b43e998a788f9a00"
os = "windows"

    [[Pango.download]]
    sha256 = "15b5623bb0b16c4c1d45674dbda532b364c34ff76183939f82438bfdd5e0daef"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+9/Pango.v1.42.4.i686-w64-mingw32.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "78fdb3ca55c03d4411465f0a9ad7bf6655a8082e"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "970fb2f9f9a8d487164c6f03bf179d168aa1e136c20137e9aa535a317d93eff6"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+9/Pango.v1.42.4.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "167393268eedc769723d593992c26341a3d2f08d"
os = "macos"

    [[Pango.download]]
    sha256 = "315289e1c42a3449bbed2b7ea9f3203eb346ad4b197604c5d7899657ea9b3fb6"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+9/Pango.v1.42.4.x86_64-apple-darwin14.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "079e2f87254bb2465a44de255cd5dde50d4d0b62"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "9eb948f78d4f06caf762855afd9bfa09784049342f235a64768871e31004b55e"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+9/Pango.v1.42.4.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "8d6babad01ff0cc40711e6fa25e0ae1f4045a6e6"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "f510ab93e7973a2f0de3fcf11d5aa5b8e86611f2db313921fc9e896e8ef8b4da"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+9/Pango.v1.42.4.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "99e9536a433413a7d973afa042842afbef895f0e"
os = "freebsd"

    [[Pango.download]]
    sha256 = "24d8f64c964f68d4b4df61a3aa53e646b7d6ede31d4dd158984b57e527618ee9"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+9/Pango.v1.42.4.x86_64-unknown-freebsd11.1.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "d44308a9abb790d928ac029b7f1660d167ea67df"
os = "windows"

    [[Pango.download]]
    sha256 = "be0ae6b025a30e37bab5f4a9778574a2d935bc1b828fb9b51414bd9d82f9a63d"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+9/Pango.v1.42.4.x86_64-w64-mingw32.tar.gz"
