[[Pango]]
arch = "i686"
git-tree-sha1 = "95da1c40c815c7edaec4c4ad4ca4cd850c89558f"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "b896884a0ef7e4d0fd70fe83def3cc909885b6e46d81095366c3dabf559999df"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+8/Pango.v1.42.4.i686-linux-musl.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "3c04c0e2793419be286c55cc2bd4fc61e26befc1"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "7bae96df81b415b1f8b3991b5512017a5cda14de48d49d5c6a0237da6b09dde3"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+8/Pango.v1.42.4.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "056e2ed5e684bd09cc9fb9d4af25489872e2bc3c"
os = "windows"

    [[Pango.download]]
    sha256 = "aaaefca64f86d4ed119a4668368f159c266aa18e9a619c54fc3a6a57a2f218bd"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+8/Pango.v1.42.4.i686-w64-mingw32.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "4f9af36b0914614191a800015949974048f469bf"
os = "windows"

    [[Pango.download]]
    sha256 = "7a085968bd5a279a4c0db19137b1a2be3bfb1283124992eb1f83796150c4080d"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+8/Pango.v1.42.4.x86_64-w64-mingw32.tar.gz"
[[Pango]]
arch = "armv7l"
git-tree-sha1 = "c3b7fb0c1703b1892a286cedc2a8f6394bdad14d"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "346eee6849ce00b7974546e377c8b6d01f1031ebdac4e2c5012dcb22f3f7c435"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+8/Pango.v1.42.4.armv7l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv7l"
git-tree-sha1 = "57ecb7bd819249c65af0eb5dff8a80610b44438d"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "21889af12eeee185b2a595e0c43e2191a974406dd88e9db93cf74ce54c74217a"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+8/Pango.v1.42.4.armv7l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "b8d03a5d5f732c71599533b109955114dce16bb6"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "7176e569bf84ecc8621d61a8af19d8f0f7fc95b6108710c728adead854eeec92"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+8/Pango.v1.42.4.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "d1b08b39b964a815c4833e387ec0e3b32275b321"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "d40ad58be4b6805427158550580c17ef7828942f84e12417981e6b84923e0c8a"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+8/Pango.v1.42.4.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "cb24ca48cc631e8c584cf9caf06a8dc467ffdb2f"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "3e37c23587e13588ce3af4a0b8bde6e3991175f019a0681ac5ccb11828439f6d"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+8/Pango.v1.42.4.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "ba0e80c2c52d2e34de0b4f29d8de5f6e4218d19e"
os = "macos"

    [[Pango.download]]
    sha256 = "4aab70a8b29c3c29eaddbb24bb1e468cadbd5c0aa8d067afc55430f3314dca52"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+8/Pango.v1.42.4.x86_64-apple-darwin14.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "4786e029cbc3f0455b54ebefc0784ab2f553b6cd"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "7e6fc515dc32705dda498fbb14da17bccd153d2aee69b3700d283c6bbc47d829"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+8/Pango.v1.42.4.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "95b4e6e3b84876e0fabbfcf88ba1cb721ea2b164"
os = "freebsd"

    [[Pango.download]]
    sha256 = "c88503e760c8dd6b15feeae3fe31d64c14828602268294a9b034006f16fa7692"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+8/Pango.v1.42.4.x86_64-unknown-freebsd11.1.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "34e5e439b630f564115c750a079b1657115fa67b"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "5c940f2b551afe39d3542c646ec2b673a4f3052a571c58815831faf87a623e1d"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+8/Pango.v1.42.4.x86_64-linux-musl.tar.gz"
