[[Pango]]
arch = "aarch64"
git-tree-sha1 = "3f72ac459eb33379a85dc4acdd35ab8bf0ac8c05"
os = "macos"

    [[Pango.download]]
    sha256 = "3c7ff6c4feeecfd5dec87d27904d87bd474d0ed829a2f94d786b2586d2c7b027"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.aarch64-apple-darwin.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "3243f3c78b390301e41a3649a08585122a67f96c"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "6c97e1210e2d2cb6f1161616b1a812a19e5642913a5bea68618f71963ea3bddc"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "371a5bc84dae7a2d6a4e609817228f78cadfb55f"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "bbc452837f54d75d5c11ab4abab4b0d2da6822b83349facbd442101f37a78e12"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "d9490b46f22bbb792d242e96523fa69164399a12"
os = "freebsd"

    [[Pango.download]]
    sha256 = "aec7209f3611fc90773cba39c06e3f7ec5dde8c08e3751b3231579dbd4e29a6d"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.aarch64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6c5ad0c046a24c169a766bad435d5cd4c94b36f8"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "82bdf3f040291447500f48d5c3fb68d88e408b058c0ea627a5877d761d3c88f8"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.armv6l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c134ccfa1663215b75556de51ebb2d254e6da3c6"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "de30439e851b40b61c13fc0e0ea915d46fd05141dbd0b92ee088f84818e4ecfe"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.armv6l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "51f05c24ad8c4d059697c6722c704c5e7a2d9c9a"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "969f0b56051cf968cd8e101b3671274b69e4126cc149c58317df56b5b224bc83"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.armv7l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2f56a1edb163b0baa1ddcd238eadbbf39458cbe6"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "67272415f7b4b4152e147054ad7e8bd699f61e01b669a74211d61835495553a4"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.armv7l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "60345803adad0ca242d2da6a47f66d2d1b2391b3"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "0ff6d5eabf4952aaac464daab257808dce1330b0796c89070e6c4557716cce93"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "e38ce0ddc37b5f94befd12a98da027523a3e1dbe"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "1c118859dd4b40ddaaed3e23a6c54abace0780a7f321495fcce4b172a0c6ae0d"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.i686-linux-musl.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "5e1b29f75e8006ec6c1ea31f4f0852e5ed2cd2e0"
os = "windows"

    [[Pango.download]]
    sha256 = "d025c28c272f6ab39905a085f257b4f1dd8ece5db8d08a8d9bfd95fd48fe325a"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.i686-w64-mingw32.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "01877811c7663a4748d1d8ea2e8673904d7c0788"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "6cec9d390161676603fbab7e040f449e3ebfa5215a6deb09bec2058dff0b4100"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "riscv64"
git-tree-sha1 = "42f8dac14048b1d6afef7ba38ea4250cf91caf01"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "06708488f539495280b5ddf1d641c8b5a37f74d0fc0c27c329b5e8f937e1272e"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.riscv64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "ec69f425eb3e0f890bd5e94e57505a16272b7845"
os = "macos"

    [[Pango.download]]
    sha256 = "f621c8b6ac4479615474a7d663c81b33f418c8493d54bbf46871e2114727748a"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.x86_64-apple-darwin.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "8e0f20c04de9b523b3877c5cfeb8d5323da6e0b3"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "0dd90f485a98fe7101fba1813c55cd300c5877b0c3e3f1f8753e68c74bcd9f4d"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "d3dfaf5f68b0f0602114255222d0c5c44ab9260f"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "a541dbb69ce55a7823c061ff85c2af51ed28a91cdc2c48ee9ca87e30b5da6889"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "33cc2d9aba61737b14f59b80e1a56cffec2f68b1"
os = "freebsd"

    [[Pango.download]]
    sha256 = "1a56c9e5d1473dec832e925210b635029062e0b6eeaf4e47d8436b05e975a57f"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.x86_64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "5a5df84653733a77f6d5c97eac3b3f077aa918a7"
os = "windows"

    [[Pango.download]]
    sha256 = "119f2b92c6cf35f983687dd9b21181f1bb64f25e1068cf2b6c4c28433e0c6529"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.1+0/Pango.v1.57.1.x86_64-w64-mingw32.tar.gz"
