[[Pango]]
arch = "aarch64"
git-tree-sha1 = "ac97f4ee2a174781bc5cde47b3118463f1c6596e"
os = "macos"

    [[Pango.download]]
    sha256 = "72a45074e09eb9b9da8246530c5f0ca8f410c405cfee6bd2517ff4c2c946c236"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.9+0/Pango.v1.50.9.aarch64-apple-darwin.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "e3e798f79275000f1eea1a0f9d50888f4ca5f825"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "451f295bb70297d90276296d78c178d48e71bd7990434e112d09be6598b94471"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.9+0/Pango.v1.50.9.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "a3b7b922f053e1fc9cb42fb919a85cf7bfe5c9bf"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "ecf1ce07102048d95aab4adaa7cb894efed57cd2468eb483283e5c53713946e1"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.9+0/Pango.v1.50.9.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0947a93b715589520e10b0758015f892898be073"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "35b4c6db53e2d0f6b6fbfda86987dd14895c28cb9ad8cbdd54bb662398b06822"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.9+0/Pango.v1.50.9.armv7l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c041681dac5135997593e35313b8a121378f1a60"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "80cbf908924784fea52e7185514349e91a2dc4506d1b03115d8782b59ed4e896"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.9+0/Pango.v1.50.9.armv7l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "6bb869e680abf1e63d07be156ac41d9f6b6e6945"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "932d72a4870edd8b0b338c363bfdda497af5d2e2c6f12f0afd357d530b0c2d33"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.9+0/Pango.v1.50.9.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "639c4c0ddceb87418fafe0adcfe1dccb7f195d06"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "6182a4b4cc18dbac9623e344d7eaa678e2d3488dd56d7c9ab0cda742a5409346"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.9+0/Pango.v1.50.9.i686-linux-musl.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "d7f9b2c6d14e19c75d661ec5cd0408b439618724"
os = "windows"

    [[Pango.download]]
    sha256 = "470504e4458c1a07e8b0db058a83b9b1bafd091f802486c8ce57d3729572dba0"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.9+0/Pango.v1.50.9.i686-w64-mingw32.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "236ebe5b95272af939cc588cda5086b95d2142b8"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "b485486526608b741c7ec94f65af0018bf8fdc21bedfc5eeb3d4d6b08a3735c4"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.9+0/Pango.v1.50.9.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "ac8ed762992b3611b17ddb12ef13209f9fd796ee"
os = "macos"

    [[Pango.download]]
    sha256 = "e3889d46fe503d309e934867d89c0cccaf22da3f1bcd82c45f32b13d40c743c2"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.9+0/Pango.v1.50.9.x86_64-apple-darwin.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "ae0f21d0d4ab66409f73619fb058836df3530089"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "6371f9dbd290d5a0ea16bf2403c87f22e5cd0f27f86841ceee0d0014b8dd8f07"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.9+0/Pango.v1.50.9.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "0f153ab09d0e6158bc55522f65b19398a4c055dc"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "9881c9759b178e38bb20cbd4a47d5e09758cea8d6ede17c54c57b0a7a545360a"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.9+0/Pango.v1.50.9.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "52a8a16d313cd74fa7f4274966ecec4c688ddbb3"
os = "freebsd"

    [[Pango.download]]
    sha256 = "329585966c8a12fff2d27358a1bd7259c1370e8bc11085aeef6d07976f812ce2"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.9+0/Pango.v1.50.9.x86_64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "e0ded3bea7869629f7292ce115f5040039a325f6"
os = "windows"

    [[Pango.download]]
    sha256 = "4b2bbb91efe39252696862d2cd7f816e2094153baefb371dd0100cf4bf7d7124"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.9+0/Pango.v1.50.9.x86_64-w64-mingw32.tar.gz"
