[[Pango]]
arch = "aarch64"
git-tree-sha1 = "6f2c40d27876e49c6460d65b072ebb532768a68a"
os = "macos"

    [[Pango.download]]
    sha256 = "e4457dc49eef2db582ab0e6e8dc4365290c3bb4da73726f1109297bed1821687"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.14+0/Pango.v1.50.14.aarch64-apple-darwin.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "955ad4d755f415728c8b7c5e495cd88635ec3749"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "470badc543d0f732fce904cc083268d6c3b6ce8ab2506f3caab1becd3418741b"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.14+0/Pango.v1.50.14.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "a12ad8849bfd37ee1dba5816f52f09d6d2c84ee7"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "69b0ea1451c46c0632141eff8069ff06b7a9c8346a436b20ad93e7549794e6d5"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.14+0/Pango.v1.50.14.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9abe03f89a3d12bcfdeacc1ab9122f07f7f07389"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "1fea2b389d4ecbaebe57bb0e0ea9bc1d0a161405515d3e67107b40e84fd2df2f"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.14+0/Pango.v1.50.14.armv7l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c7605c0031d9a3017cc364e632ca1e375892cb24"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "5dd56ec066c47722b9fd71ab3f1544804d49518ee6f010e5c71e9ed9f5ced961"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.14+0/Pango.v1.50.14.armv7l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "4d18e3010c72caaadffc32e507bb34955b1d46e5"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "a531a77446a2cdb3698b6fdf2a16f4165d1cf213c9043150c76bb064b788338c"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.14+0/Pango.v1.50.14.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "13f5fa6eb5fec3100263c1c2e77682334ac0502c"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "836d4a2a0c59cd573d28b3abaafe4e4db0749908e2e8cc8332cd08df3ed38234"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.14+0/Pango.v1.50.14.i686-linux-musl.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "0f27da3edb00fdc52e50aabaaef8cfd0df8674df"
os = "windows"

    [[Pango.download]]
    sha256 = "c8fa29ac141fc8cca016b9d5d64ec326d05431e1a1b209b79452355228f86091"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.14+0/Pango.v1.50.14.i686-w64-mingw32.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "06ab55090612ed94978dc10792eb70c41b4a7872"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "1d1d438dc9072ac7d2317a1b0c541e2e8ee8ca6683910f78be7e6da0861c7fcf"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.14+0/Pango.v1.50.14.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "a79c326639dc580d203f5962eebbb66df348c9ce"
os = "macos"

    [[Pango.download]]
    sha256 = "5a8444b16f216098e456e284a22a72e717858a58f4b5105ca216f2f31fe230d1"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.14+0/Pango.v1.50.14.x86_64-apple-darwin.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "57a2adf6148eab124016172e61e7850ec8bcc217"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "8141a69a5e71f33721ac5cfd1afc30e0226571d0792f0f880d9e901c53c677aa"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.14+0/Pango.v1.50.14.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "e864587472a6d9e37174b9fa78b2a9b93a4b2b6e"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "05124a8240985c99ea6f3f5802c6b42143a7d5908d4726008be2256094531186"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.14+0/Pango.v1.50.14.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "5237ff5c1c3d4f4e8236ed9b58e7434f69c79604"
os = "freebsd"

    [[Pango.download]]
    sha256 = "3128748f9966c8e1a6a4e3c601f0b08425cf1486cd7cf0e167c51d630a761ac1"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.14+0/Pango.v1.50.14.x86_64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "56b50e15c4bf17d87081795ed94c739d3a24271c"
os = "windows"

    [[Pango.download]]
    sha256 = "d56f216c49acc64c328e7c2283734b05369b5b335bec25d3f8fad538e55ff930"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.50.14+0/Pango.v1.50.14.x86_64-w64-mingw32.tar.gz"
